// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/CommandGroup1.h"
#include "Commands/a_debug.h"
#include "Commands/a_drive_move_dist.h"
#include "Commands/a_drive_move_stra.h"
#include "Commands/a_drive_move_time.h"
#include "Commands/a_drive_strafe_dist.h"
#include "Commands/a_drive_turn_angle.h"
#include "Commands/a_grabber_grab.h"
#include "Commands/a_grabber_push.h"
#include "Commands/a_grabber_ungrab.h"
#include "Commands/a_lift_bottom.h"
#include "Commands/a_lift_move_dist.h"
#include "Commands/a_lift_move_time.h"
#include "Commands/a_lift_setup.h"
#include "Commands/a_lift_top.h"
#include "Commands/auto_3totes.h"
#include "Commands/auto_3totes_norc.h"
#include "Commands/oi_Grabber.h"
#include "Commands/oi_HDrive.h"
#include "Commands/oi_Lift.h"
#include "Commands/sd_drive_turn_angle.h"
#include "Commands/sd_lift_dist.h"
#include "Commands/sd_move_dist.h"
#include "Commands/sd_strafe_dist.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "Xbox.h"

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

	//aux = new Joystick(1);
	
	driver = new Joystick(0);

     
        // SmartDashboard Buttons
	SmartDashboard::PutData("oi_HDrive", new oi_HDrive());

	SmartDashboard::PutData("auto_3totes", new auto_3totes());

	SmartDashboard::PutData("a_lift_top", new a_lift_top());

	SmartDashboard::PutData("a_lift_bottom", new a_lift_bottom());

	SmartDashboard::PutData("a_grabber_ungrab", new a_grabber_ungrab());

	SmartDashboard::PutData("a_grabber_grab", new a_grabber_grab());

	SmartDashboard::PutData("oi_Lift", new oi_Lift());

	SmartDashboard::PutData("sd_move_dist", new sd_move_dist());

	SmartDashboard::PutData("sd_lift_dist", new sd_lift_dist());

	SmartDashboard::PutData("sd_drive_turn_angle", new sd_drive_turn_angle());

	SmartDashboard::PutData("sd_strafe_dist", new sd_strafe_dist());

	SmartDashboard::PutData("a_grabber_push", new a_grabber_push());

	SmartDashboard::PutData("auto_3totes_norc", new auto_3totes_norc());

	SmartDashboard::PutData("Command Group 1", new CommandGroup1());

	SmartDashboard::PutData("a_lift_setup", new a_lift_setup());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	xbox = new Xbox(1);
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Joystick* OI::getAux() {
	return aux;
}

Joystick* OI::getDriver() {
	return driver;
}


// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

Xbox* OI::getXbox(){
	return xbox;
}
